pub const MAX_ZOOMOUT_THRESHOLD: f32 = 70.0;
pub const MAX_ZOOMIN_THRESHOLD: f32 = 0.40;
pub const TEXT_VISIBILITY_ZOOM_THRESHOLD: f32 = 3.0;
pub const BUILDING_VISIBILITY_ZOOM_THRESHOLD: f32 = 12.0;
